'use client'

import type { Metadata } from 'next'
import { useEffect } from 'react'
import { Inter } from 'next/font/google'
import './globals.css'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { AuthProvider } from '@/context/auth'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const queryClient = new QueryClient({})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  useEffect(() => {
    axios.defaults.withCredentials = true
    const fetchCSRFToken = async () => {
      const response = await axios.get(
        `${process.env.NEXT_PUBLIC_API_URL}/csrf`,
        { withCredentials: true },
      )
      const data = response.data
      axios.defaults.headers.common['X-CSRFToken'] = data.csrf_token
    }
    fetchCSRFToken()
  }, [])

  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-stone-300 text-stone-900 dark:bg-black`}
      >
        <nav className="hidden md:block">
          <h1>Famiibo</h1>
        </nav>
        <AuthProvider>
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
