import React from 'react'
import {
  Restaurant,
  AccountBalance,
  AttachMoney,
  ShoppingCart,
  LocalGroceryStore,
  DirectionsCar,
  Home,
  School,
  Work,
  FitnessCenter,
  LocalHospital,
  LocalPharmacy,
  LocalDining,
  LocalCafe,
  LocalBar,
  LocalLibrary,
  LocalMovies,
  LocalOffer,
  LocalParking,
  LocalPlay,
  LocalPostOffice,
  LocalPrintshop,
  LocalSee,
  LocalShipping,
  LocalTaxi,
} from '@mui/icons-material'

const iconMap: { [key: string]: JSX.Element } = {
  Restaurant: <Restaurant />,
  AccountBalance: <AccountBalance />,
  AttachMoney: <AttachMoney />,
  ShoppingCart: <ShoppingCart />,
  LocalGroceryStore: <LocalGroceryStore />,
  DirectionsCar: <DirectionsCar />,
  Home: <Home />,
  School: <School />,
  Work: <Work />,
  FitnessCenter: <FitnessCenter />,
  LocalHospital: <LocalHospital />,
  LocalPharmacy: <LocalPharmacy />,
  LocalDining: <LocalDining />,
  LocalCafe: <LocalCafe />,
  LocalBar: <LocalBar />,
  LocalLibrary: <LocalLibrary />,
  LocalMovies: <LocalMovies />,
  LocalOffer: <LocalOffer />,
  LocalParking: <LocalParking />,
  LocalPlay: <LocalPlay />,
  LocalPostOffice: <LocalPostOffice />,
  LocalPrintshop: <LocalPrintshop />,
  LocalSee: <LocalSee />,
  LocalShipping: <LocalShipping />,
  LocalTaxi: <LocalTaxi />,
}

export default iconMap
